# Update repositories cache and install tomcat7 package
- apt: name=tomcat7 update_cache=yes

# libcairo2-dev
- apt: name=libcairo2-dev

# libpng12-dev
- apt: name=libpng12-dev

# libossp-uuid-dev
- apt: name=libossp-uuid-dev

# libfreerdp-dev
- apt: name=libfreerdp-dev

# libpango1.0-dev
- apt: name=libpango1.0-dev

# libssh2-1-dev
- apt: name=libssh2-1-dev

# libvncserver-dev
- apt: name=libvncserver-dev

# libpulse-dev 
- apt: name=libpulse-dev 

# libssl-dev
- apt: name=libssl-dev

# libvorbis-dev
- apt: name=libvorbis-dev

# copying old sources.list
- command: cp /etc/apt/sources.list /etc/apt/sources.list.orig
 
# Add a line to a sources.list
- lineinfile: dest=/etc/apt/sources.list line="deb http://100.64.1.11/ubuntu trusty universe" create=yes

# Add a line to a sources.list
- lineinfile: dest=/etc/apt/sources.list line="deb-src http://100.64.1.11/ubuntu trusty universe" insertafter=EOF

# Update repositories cache and install libtelnet-dev package
- apt: name=libtelnet-dev update_cache=yes

# revert to original sources.list
- command: mv /etc/apt/sources.list.orig /etc/apt/sources.list

# Run the equivalent of "apt-get update" as a separate step
- apt: update_cache=yes

- name: download file with sha256 check
  get_url: url=https://github.com/seanx820/guac-cum/blob/master/guacamole_install.tar.gz?raw=true dest=/home/cumulus/guacamole_install.tar.gz
  
# gunzip
- command: gunzip -f /home/cumulus/guacamole_install.tar.gz

# tar
- command: tar -xvf /home/cumulus/guacamole_install.tar -C /

- name: Creates directory
  file: path=/usr/share/tomcat7/.guacamole state=directory

#- file: src=/file/to/link/to dest=/path/to/symlink owner=foo group=foo state=link
#- name: Create symlink to example.com
#  file: src=/usr/share/tomcat7/.guacamole/ dest=/etc/guacamole/guacamole.properties state=link

# make symlink, for some reason the file command above commented out did not work
- command: ln -sf /etc/guacamole/guacamole.properties /usr/share/tomcat7/.guacamole/

# make libraries available to everything
- command: ldconfig

# Example action to restart service httpd, in all cases
- service: name=tomcat7 state=restarted

# Example action to restart service httpd, in all cases
- service: name=guacd state=restarted
